trigger:
- main
 
pool:
  vmImage: ubuntu-latest

#variables:
#   -group: Platform-Versions 

steps:
 
- task: TerraformInstaller@2
  inputs:
    terraformVersion: '1.10.5'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    backendType: 'azurerm'
    allowTelemetryCollection: false

 
- task: TerraformCLI@1
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/AVM-TERRAFORM-LABS'
    allowTelemetryCollection: true